#!/bin/sh 
INITRC=/etc/rc.d/S99squidsetup
RCL=/etc/rc.local

#fill in your custom commands here
sip=`uci get network.mesh.ipaddr`
rm $INITRC
mkdir /home/squid
mkdir /home/squid/log
mkdir /home/squid/cache
chmod -R 777 /home/squid
squid -z
sed "/exit 0/d" $RCL > /tmp/RCL
mv -f /tmp/RCL $RCL
#dunno why next line was ever in here...
#echo "sh /etc/fabfi-scripts/upgrade-post" >> $RCL
echo "ln -s /home/squid/log/ /var/logs" >> $RCL
echo "squid -D" >> $RCL
echo "exit 0" >> $RCL
echo "iptables -t nat -A PREROUTING -p tcp -d ! 10.0.0.0/8 --dport 80 -j DNAT --to ${sip}:3128" > /etc/firewall.user
sleep 1
reboot &

