#!/bin/ash

case $1 in

	lat ) 
		uci get olsrd.@LoadPlugin[1].lat
		;;
	lon ) 
		uci get olsrd.@LoadPlugin[1].lon
		;;
	
	neigh_ip )

		cat /var/run/latlon.js | grep -i node | cut -d "(" -f 2 | cut -d "," -f 1 | tr -d "'"
		;;

	neigh_hostname )
		cat /var/run/latlon.js | grep -i node | cut -d "," -f 6 | cut -d ")" -f 1 | tr -d "'"
		;;

	neigh_lat )
		cat /var/run/latlon.js | grep -i node | cut -d "," -f 2			
		;;

	neigh_lon )
                cat /var/run/latlon.js | grep -i node | cut -d "," -f 3
                ;;
	

esac
